### PR TITLE
Add AWS image name parser

### LINKED ISSUE #34: Get extra image data from AWS image names
The image names on AWS provide some additional information that might be useful in the locator. For example, the distinction between beta and non-beta images is really only made within the image name itself:

```
> $ aws --region=us-east-1 ec2 describe-images --owner 309956199498 --filter "Name=is-public,Values=true" | jq -r ".Images[].Name" | sort
RHEL-6.10_HVM-20210318-x86_64-0-Hourly2-GP2
RHEL-7.9_HVM-20210208-x86_64-0-Hourly2-GP2
RHEL-7.9_HVM-20211005-x86_64-0-Hourly2-GP2
RHEL-7.9_HVM-20220222-x86_64-0-Hourly2-GP2
RHEL-7.9_HVM-20220512-x86_64-1-Hourly2-GP2
RHEL-8.1.0_HVM-20210907-arm64-0-Hourly2-GP2
RHEL-8.1.0_HVM-20210907-x86_64-0-Hourly2-GP2
RHEL-8.2.0_HVM-20210907-arm64-0-Hourly2-GP2
RHEL-8.2.0_HVM-20210907-x86_64-0-Hourly2-GP2
RHEL-8.3.0_HVM-20201031-arm64-0-Hourly2-GP2
RHEL-8.3.0_HVM-20201031-x86_64-0-Hourly2-GP2
RHEL-8.3.0_HVM-20201222-arm64-0-Hourly2-GP2
RHEL-8.3_HVM-20210209-arm64-0-Hourly2-GP2
RHEL-8.3_HVM-20210209-x86_64-0-Hourly2-GP2
RHEL-8.4.0_HVM-20210504-arm64-2-Hourly2-GP2
RHEL-8.4.0_HVM-20210504-x86_64-2-Hourly2-GP2
RHEL-8.4.0_HVM-20210825-arm64-0-Hourly2-GP2
RHEL-8.4.0_HVM-20210825-x86_64-0-Hourly2-GP2
RHEL-8.4.0_HVM_BETA-20210309-arm64-1-Hourly2-GP2
RHEL-8.4.0_HVM_BETA-20210309-x86_64-1-Hourly2-GP2
RHEL-8.5.0_HVM-20211103-arm64-0-Hourly2-GP2
RHEL-8.5.0_HVM-20211103-x86_64-0-Hourly2-GP2
RHEL-8.5.0_HVM_BETA-20210902-arm64-5-Hourly2-GP2
RHEL-8.5.0_HVM_BETA-20210902-x86_64-5-Hourly2-GP2
RHEL-8.5_HVM-20220127-arm64-3-Hourly2-GP2
RHEL-8.5_HVM-20220127-x86_64-3-Hourly2-GP2
RHEL-8.6.0_HVM-20220503-arm64-2-Hourly2-GP2
RHEL-8.6.0_HVM-20220503-x86_64-2-Hourly2-GP2
RHEL-8.6.0_HVM_BETA-20220302-arm64-5-Hourly2-GP2
RHEL-8.6.0_HVM_BETA-20220302-x86_64-5-Hourly2-GP2
RHEL-8.7.0_HVM_BETA-20220830-arm64-0-Hourly2-GP2
RHEL-8.7.0_HVM_BETA-20220830-x86_64-0-Hourly2-GP2
RHEL-9.0.0_HVM-20220513-arm64-0-Hourly2-GP2
RHEL-9.0.0_HVM-20220513-x86_64-0-Hourly2-GP2
RHEL-9.0.0_HVM_BETA-20211026-arm64-10-Hourly2-GP2
RHEL-9.0.0_HVM_BETA-20211026-x86_64-10-Hourly2-GP2
RHEL-9.1.0_HVM_BETA-20220829-arm64-0-Hourly2-GP2
RHEL-9.1.0_HVM_BETA-20220829-x86_64-0-Hourly2-GP2
RHEL_HA-7.9_HVM-20210315-x86_64-2-Hourly2-GP2
RHEL_HA-8.3_HVM-20210315-x86_64-1-Hourly2-GP2
RHEL_HA-8.4.0_HVM-20210504-x86_64-2-Hourly2-GP2
RHEL_HA-8.5.0_HVM-20211103-x86_64-0-Hourly2-GP2
RHEL_HA-8.5.0_HVM_BETA-20210902-x86_64-5-Hourly2-GP2
RHEL_HA-8.5_HVM-20220127-x86_64-3-Hourly2-GP2
RHEL_HA-8.6.0_HVM-20220503-x86_64-2-Hourly2-GP2
RHEL_HA-9.0.0_HVM-20220513-x86_64-0-Hourly2-GP2
RHEL_HA-9.0.0_HVM_BETA-20211026-x86_64-10-Hourly2-GP2
RHEL-SAP-8.1.0_HVM-20211007-x86_64-0-Hourly2-GP2
RHEL-SAP-8.2.0_HVM-20211007-x86_64-0-Hourly2-GP2
```

### PR DESCRIPTION
**Pull request by major**
Parse additional information about AWS images using their name.

Fixes #34

Signed-off-by: Major Hayden <major@redhat.com>

### CODE REVIEW

**Review by FKolwa — APPROVED** [review]
I've tried to break that regex as hard as I could and failed.
Great job ;)

**Comment by major** [comment]
@FKolwa Hah, thanks. I kept thinking I could get creative with splitting on dashes and underscores, but then I realized that it would be easier with a regex of some sort. 🤷🏻‍♂️

**Comment by FKolwa** [comment]
Btw. Who decides about this naming strategy? Is it Red Hat? Is it Amazon? Is there some guarantee that future image names will adhere to this or could we end up with a "rhel-9.1_amazing_blueberry-HVM-HOURLY-2023" at some point?

**Comment by major** [comment]
That's a good question. Based on what I've seen so far for hourly/cloud access, it looks like we are the ones that decide.

**Pull request merged**
